### PR TITLE
fix: add info for apps without budgets

### PR DESCRIPTION
**Pull request by reneaaron**

### CODE REVIEW

**Comment by rolznz** [comment]
@reneaaron nice!

I noticed one thing though, it doesn't work so well for apps that don't have spending permission. Could we have a different design for those ones?

**Comment by reneaaron** [comment]
@rolznz What would you like to see for these apps?

**Comment by rolznz** [comment]
@reneaaron should we at least add a label like "Read only"? what do you think?

e.g. if we think about adding Clams as a connection

**Comment by rolznz** [comment]
@reneaaron I did this for now, let's improve it again in a follow up PR
image

**Pull request merged**
