### PR TITLE
chore: update ldk-node-go and glalby-go to use MSVC-linked libraries

### PR DESCRIPTION
**Pull request by rdmitr**

### CODE REVIEW

**Comment by rdmitr** [comment]
@im-adithya updated ldk-node and glalby bindings to use MSVC-linked libraries on Windows.

**Comment by im-adithya** [comment]
For some reason I can't see the build files for Windows and Linux [here](https://github.com/getAlby/nostr-wallet-connect-next/actions/runs/9536492120)

**Comment by rdmitr** [comment]
@im-adithya that's super weird — some kind of github issue maybe? Both artifacts are available on the corresponding build job pages, under the "Run actions/upload-artifact@v4" step 🤔

**Comment by im-adithya** [comment]
Yeah ig it's a GitHub issue, re-ran the checks and got the build files now!

https://github.com/getAlby/nostr-wallet-connect-next/actions/runs/9536492120

**Comment by im-adithya** [comment]
Tried the Windows build but it still shows the same popup

image

**Comment by rdmitr** [comment]
@im-adithya my bad 🤦‍♂️ I updated the bindings library versions but copied the old libraries in the workflow. Fixed now. Tried it on my machine with MinGW unavailable — worked fine!

**Review by im-adithya — APPROVED** [review]
tACK, works great now 🚀

**Pull request merged**
