### PR TITLE
fix: add legal copy

### PR DESCRIPTION
**Pull request by reneaaron**

### CODE REVIEW

**Comment by bumi** [comment]
Shouldn't we link this externally?

**Review by MoritzKa — COMMENTED** [review]
Thanks for adding the ToS. I made some adjustments to the copy because the Alby Pro plan is not available yet. So a made it more generic by referring to Services.

**Comment by bumi** [comment]
is this final?

**Comment by MoritzKa** [comment]
The EULA is final for now.

**Pull request merged**
