### PR TITLE
Support ARM6 build

### PR DESCRIPTION
**Pull request by rdmitr**
This PR upgrades glalby-go and ldk-node-go dependencies to their repository versions that contain prebuilt arm6-linux-gnueabihf libraries.

### CODE REVIEW

**Comment by rdmitr** [comment]
Prebuild binary and libraries ready to be used on Raspberry Pi:

[nostr-wallet-connect-bin.tgz](https://github.com/getAlby/nostr-wallet-connect-next/files/15029579/nostr-wallet-connect-bin.tgz)

**Comment by rdmitr** [comment]
Rebuild binary and libraries with pre-build frontend:
[nostr-wallet-connect-bin.tgz](https://github.com/getAlby/nostr-wallet-connect-next/files/15044647/nostr-wallet-connect-bin.tgz)

**Comment by reneaaron** [comment]
@rdmitr What is missing here to get this build up and running? Can we integrate that into our GitHub workflow, too? 

It would be awesome if every master build would include such a package automatically.

**Comment by rdmitr** [comment]
@reneaaron 

The PR itself is ready. Only two things are changed here:

- Rust bindings' versions are bumped;
- Breez is disabled for RPi builds.

However, I have almost no experience with setting up github workflows, so I will need your assistance here 🙏  I can offer support with the cross-compilation part, of course.

**Comment by rdmitr** [comment]
@reneaaron I came up with a Github action to build the package but I cannot test it — looks like running actions outside of main branch is not possible (or disabled?). Could you please take a look?

**Pull request merged**
