### PR TITLE
Implement CloseChannel() for Greenlight

### PR DESCRIPTION
**Pull request by rdmitr**
- [x] update saving credentials to use encryption key instead of mnemonic - @rolznz 
- [x] update glalby bindings @rdmitr

### CODE REVIEW

**Comment by rolznz** [comment]
glalby-go bindings need to be updated - but I'm not sure they work until the greenlight issue is addressed. I will follow up on this next week.

**Comment by rolznz** [comment]
@rdmitr could you merge the latest greenlight changes into glalby and generate new bindings, then consume them in this PR?

**Comment by rdmitr** [comment]
@rolznz I updated the greenlight dependency in glalby but unfortunately it led to a breaking API change — could you please take a look? https://github.com/getAlby/glalby/pull/11

**Comment by rolznz** [comment]
@rdmitr can you let me know when you have updated the bindings? I need to make a few changes to how the credentials are saved before I can merge this PR.

**Pull request merged**
