### PR TITLE
Implement RedeemOnchainFunds() for LDK and Greenlight

### PR DESCRIPTION
**Pull request by rdmitr**

### CODE REVIEW

**Comment by rolznz** [comment]
Dependent upon https://github.com/getAlby/nostr-wallet-connect-next/issues/132

**Comment by rolznz** [comment]
For Greenlight regarding failure to withdraw funds:

I got this reply:
> Hi Roland, thanks for reporting. We are currently dealing with a bunch of things that werent quite ready to handle the scale up last week. One of them was adding a load balancer, which has a shorter keepalive interval, and drops connections that were inactive for several seconds. We have a patch for the client library, but need to address a slow notification first which would otherwise worsen. So the command was delivered but the connection was dropped due to a slow response.

I guess we need to wait for them to apply the fix, and then update glalby to use the latest greenlight version.

**Comment by rolznz** [comment]
LDK works well!

**Comment by rolznz** [comment]
I wonder if we should just merge this PR and update glalby bindings once the greenlight issue is fixed.

**Comment by rolznz** [comment]
@rdmitr does that sound ok to you?

**Comment by rolznz** [comment]
@rdmitr we need to update the glalby bindings to support mac first though - could you update them here https://github.com/getAlby/glalby-go/pull/5 and then consume the new commit hash?

**Comment by rdmitr** [comment]
@rolznz the bindings have been updated and merged 👍

**Pull request merged**
