### PR TITLE
fix: delete old ldk log files on startup

### PR DESCRIPTION
**Pull request by rolznz**
Temporary workaround for https://github.com/getAlby/nostr-wallet-connect-next/issues/206

### CODE REVIEW

**Comment by rdmitr** [comment]
Unfortunately, there's no straightforward way to implement this in LDK. I have added a periodic log cleanup routine in NWC instead. WDYT? @rolznz

**Comment by bumi** [comment]
Using something like https://docs.rs/file-rotate/latest/file_rotate/ in this logger does not make sense? https://github.com/getAlby/ldk-node/blob/6477babffdee490e9ebd729da7f827a5027a1990/src/logger.rs

**Comment by rdmitr** [comment]
> Using something like https://docs.rs/file-rotate/latest/file_rotate/ in this logger does not make sense? https://github.com/getAlby/ldk-node/blob/6477babffdee490e9ebd729da7f827a5027a1990/src/logger.rs

Not really, I'm afraid. Since they (LDK) open log file for each log line (which is quite weird), that seems to be very inefficient. `file_rotate` will have to check file sizes (or count lines, which is much worse) on every log attempt. Also, this library seems to be unable to delete old files.

**Comment by bumi** [comment]
yeah, when I saw that logger I was wondering why the implement that like this and on their own. there should be some default well built log loggers.

**Comment by rdmitr** [comment]
>  there should be some default well built log loggers

It is even simpler than that, usually. Rust libraries are not even supposed to instantiate and configure loggers internally. The idiomatic approach is to use the `log` crate which provides "frontend" logging macros like `debug!()`, `info!()`, `error!()`, etc. The users of the library pick whatever logging backend they prefer and configure it according to their needs.

To be fair, in case of LDK this is a bit different, since LDK is supposed to be used in apps written in different languages through FFI, and these apps are unlikely to be able to easily integrate a Rust logging backend. But it could have been bundled with LDK anyways 🤔 I am somewhat puzzled, too

**Comment by rdmitr** [comment]
> edit: I would actually also like to log to STDOUT and let the log management be done externally

That's doable but has to be implemented in NWC as well as all client libraries for consistency

**Pull request merged**
