### PR TITLE
chore: remove balance cards in wallet screen

### PR DESCRIPTION
**Pull request by im-adithya**
# Screenshot

Screenshot 2024-07-02 at 4 45 12 PM

### CODE REVIEW

**Review by stackingsaunter — CHANGES_REQUESTED** [review]
- change Buy Bitcoin to "Buy"
- Delete description of the page
- Would be nice if Send and Receive are the same width (eg (144px, w-36)

**Comment by bumi** [comment]
> change Buy Bitcoin to "Buy"

when I added the button I initially had "Buy" but then was wondering what am I buying?

**Comment by im-adithya** [comment]
+1 didn't change that, the screenshot has the updated changes, can merge now!

**Review by rolznz — APPROVED** [review]
utACK

**Review by reneaaron — APPROVED** [review]
tACK

**Pull request merged**
