### PR TITLE
Build Wails app for macOS, Linux, Windows

### PR DESCRIPTION
**Pull request by rdmitr**

### CODE REVIEW

**Comment by bumi** [comment]
The macos application works well, super cool.

We need to update the name to albyhub for now and set an app icon (cc @stackingsaunter any idea what we should use here?) 
@im-adithya can you look into the code signing for mac and potentially windows: https://wails.io/docs/guides/signing/

**Comment by rdmitr** [comment]
@bumi the name is changed now 👍

**Comment by rdmitr** [comment]
Well, bummer. It did not work for macOS because of this little pesky bug in Wails: https://github.com/wailsapp/wails/issues/2290

Should we change the `"name"` field in wails.json from nostr-wallet-connect to albyhub? That would fix the issue.

**Comment by bumi** [comment]
yes, we should change the name. albyhub might get changed also but it is for sure not `nostr-wallet-connect`. so we should change this.

**Comment by rdmitr** [comment]
@bumi seems to be fixed now!

**Comment by stackingsaunter** [comment]
We can use this icon for now
icon

**Pull request merged**
